CREATE TABLE STATION(
  STATION_ID BIGSERIAL PRIMARY KEY,
  STATION_NAME VARCHAR(64) NOT NULL,
  STATION_IMAGE VARCHAR(100) NOT NULL UNIQUE,
  STATION_PRICING DECFLOAT(4) NOT NULL,
  STATION_ADDRESS VARCHAR(64)
);
